### ISSUE TITLE
spring 4.3 support

### ISSUE THREAD

**Issue by jimirocks** [martiner/gooddata-java#117]
we should consider, how can we support use with spring4, there are at least two issues:

- [x] spring4 depends on CloseableHttpClient, but GoodDataHttpClient doesn't extend it - tried some [workaround](https://github.com/martiner/gooddata-java/compare/jmi-spring4?expand=1) , but no luck yet
- [x] spring4 forces jackson2 - there is some jackson1 bridge in gooddata private repos, but how to use it in public?

**Comment by pirkogdc** [comment]
The first issue seems to be resolved from spring 4.2 - see https://jira.spring.io/browse/SPR-12826

**Comment by pirkogdc** [comment]
bugfix if "obtaing TT problem": https://github.com/gooddata/gooddata-http-client/pull/18

**Comment by martiner** [comment]
obtaining TT problem fixed in gooddata-java v. 0.9.0

**Comment by james-hu** [comment]
What is the status now? I've done some code change and implemented a successful work around in last year. I am wondering if Spring 4 and Jackson 2 is now officially supported.

**Comment by pirkogdc** [comment]
The current status:
* waiting for spring 4.2.GA because of https://jira.spring.io/browse/SPR-12826 (mentioned above) - you can extend `GoodData` and override `createHttpClient` method to supply some closeable http client fake wrapping original `GoodDataHttpClient`. Moreover you need to supply your own Jackson1MappingConverter to RestTemplate (usual trick is to copy that class from spring3 to your classpath)
* we need to resolve #197 and #99 first - unfortunately, we also can't use gooddata-http-client 0.9.0 since there is a logout bug - you can possibly use 0.9.0 when you are happy with broken logout and don't need  `DataStoreService` - however I wouldn't recommend that.

We are working on all the issues mentioned and the release of spring 4.2 should come next week. Unfortunately I can't promise any specific date since most of the job is still free time...

**Comment by james-hu** [comment]
thanks for the update. yes solving the logout/concurrency/authentication issue is more urgent.

**Comment by martiner** [comment]
#237

**Comment by pirkogdc** [comment]
Since we upgraded to jackson 2.7.0 in #254, we are now forced to wait for spring 4.3 which [should be compatible](https://jira.spring.io/browse/SPR-13853) with jackson 2.7.0. 

The spring 4.3 GA is [planned](https://jira.spring.io/browse/SPR?selectedTab=com.atlassian.jira.jira-projects-plugin:roadmap-panel) to the end of May
